Problema 1: Creación de arrays con Numpy.

a)Crear dos arrays de NumPy y asignarlos en variables. El primero debe ser de 1 dimensión y el segundo de 2 dimensiones. Aplicar en cada uno los métodos shape, ndim y size.
b)Crear un array de ceros de dimensión (3,3) y un array de unos de dimensión (2,4).
c)Crear un array definido con valores en el intervalo abierto [10,30) con un step de 2.
d)Crear dos arrays de 2D con valores aleatorios de la distribución normal. Utilizar np.random.randn() y np.random.normal(). ¿Cuáles son las diferencias?
e)Crear un array con el comando linspace.

Problema 2: Operaciones con arrays en NumPy.

a)Crear dos arrays y aplicar las operaciones arr1 + arr2 y arr1*arr2. ¿Qué condiciones deben cumplir arr1 y arr2?
b)Verificar la multiplicación de un escalar por un array.
c)De un array de 2D obtener la matriz traspuesta.
d)Realizar la multiplicación de dos matrices de dimensiones apropiadas.

Problema 3: Indexación y slicing de arrays de NumPy.

a) Crear un array de dimensión (4,4) y extraer: el elemento de la fila 3 y columna 2; la segunda fila; y la tercera columna.
b) Del array del ejercicio anterior, ¿Qué pasa si hacemos arr[1] = np.array([10,10,10,10])?
c) ¿Y qué pasa si hacemos arr[1] = 99?


Problema 4: Manipulación de arrays en NumPy.

a)Crear un array de 12 elementos en una fila. Utilizar el comando reshape(). ¿Qué argumentos de entrada puede tomar? Mostrar dos ejemplos.
b)En el array del ejercicio anterior, aplicar el comando split(). Mostrar 3 ejemplos.
c)Crear dos arrays de 1D y usar el operador concatenate. Luego usar el mismo operador en dos arrays de dimensión (2,2). Probar con el parámetro axis= 0, y axis=1.


Problema 5: Operaciones estadísticas en NumPy.
a)Crear un array de dimensión (3,3) y aplicar los métodos mean(), std(), var() y sum().
b)Repetir el ejercicio anterior utilizando el parámetro axis=0 y axis=1.


Problema 6: Utilización de booleanos en NumPy.
a)Crear un arreglo de 4 elementos y aplicar la máscara [False, True, True, False]. ¿Qué resulta?
b)Crear un arreglo unidimensional de números enteros aleatorios y filtrar por los valores mayores al promedio, números impares y números pares menores al promedio.
c) En un arreglo bidimensional A de valores aleatorios enteros, ¿qué diferencia hay entre hacer A > A.mean() y A [A> A.mean()?

Problema 1: Creación de arrays con Numpy.

a)Crear dos arrays de NumPy y asignarlos en variables. El primero debe ser de 1 dimensión y el segundo de 2 dimensiones. Aplicar en cada uno los métodos shape, ndim y size.


In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

b=np.array([
    [2,4,6],[7,2,4]
])

print(b)

print(a.shape)
print(a.ndim)
print(a.size)

print(b.shape)
print(b.ndim)
print(b.size)

[ 1  2  3  4  5  6  7  8  9 10]
[[2 4 6]
 [7 2 4]]
(10,)
1
10
(2, 3)
2
6


b)Crear un array de ceros de dimensión (3,3) y un array de unos de dimensión (2,4).


In [2]:
a=np.zeros([3,3])
print(a)
b=np.ones([2,4])
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


c)Crear un array definido con valores en el intervalo abierto [10,30) con un step de 2.


In [3]:
a=np.arange(10,30,2)
print(a)


[10 12 14 16 18 20 22 24 26 28]


d)Crear dos arrays de 2D con valores aleatorios de la distribución normal. Utilizar np.random.randn() y np.random.normal(). ¿Cuáles son las diferencias?

En el contexto de la probabilidad y la estadística, un aleatorio uniforme se refiere a una distribución de probabilidad en la que todos los valores dentro de un rango específico tienen la misma probabilidad de ocurrir. Se dice que son equitativamente probables.

Imaginemos una urna llena de pelotas numeradas del 1 al 10. Si extraemos una pelota al azar, cada número tiene la misma probabilidad de ser seleccionado (1/10). Esta es una analogía simple de una distribución aleatoria uniforme.

Matemáticamente, una variable aleatoria continua con distribución uniforme X en el intervalo [a, b] se define por su función de densidad de probabilidad (f.d.p.):

f(x) = 1/(b - a)  para a ≤ x ≤ b

Donde:

a es el límite inferior del intervalo.
b es el límite superior del intervalo.

La f.d.p. nos indica la probabilidad de que X tome un valor específico dentro del intervalo. En este caso, la probabilidad es constante en todo el rango, lo que significa que todos los valores son igualmente probables.

Propiedades de la distribución aleatoria uniforme:

Media: La media de una variable aleatoria uniforme continua es igual al punto medio del intervalo: (a + b) / 2.

Varianza: La varianza es igual a (b - a)^2 / 12.

Moda: La distribución aleatoria uniforme no tiene una moda única, ya que todos los valores dentro del intervalo son igualmente probables.


In [4]:
a=np.random.randn(10,2)
print(a)

[[-1.95623381  0.24239654]
 [ 0.68752959  0.31433435]
 [ 0.37702998 -0.37718455]
 [ 0.20045965 -2.68764495]
 [ 1.33611362 -0.49511878]
 [ 0.01971936 -0.75396598]
 [ 1.02474148 -0.06688304]
 [ 0.69391694  0.16975491]
 [-1.23409246 -0.43226127]
 [ 0.16816376 -1.08060374]]


Un número aleatorio normal se genera a partir de una distribución normal, la cual es una distribución de probabilidad en forma de campana que describe la frecuencia con la que ocurren eventos aleatorios.

En una distribución normal, la mayoría de los valores se agrupan alrededor de un valor central (media) y la probabilidad de encontrar valores alejados de la media disminuye rápidamente a medida que nos alejamos de ella.

La distribución normal se caracteriza por dos parámetros importantes:

Media (µ): Representa el valor promedio de la distribución.
Desviación estándar (σ): Indica qué tan dispersos están los valores alrededor de la media. Una desviación estándar mayor implica una mayor dispersión.

Propiedades de la distribución normal:

Forma de campana: La gráfica de la distribución normal tiene una forma de campana simétrica, con la media en el punto más alto.

68% dentro de 1σ: El 68% de los valores aleatorios generados a partir de una distribución normal se encuentran dentro de un intervalo de ±1 desviación estándar alrededor de la media.

95% dentro de 2σ: El 95% de los valores aleatorios se encuentran dentro de un intervalo de ±2 desviaciones estándar alrededor de la media.

99,7% dentro de 3σ: El 99,7% de los valores aleatorios se encuentran dentro de un intervalo de ±3 desviaciones estándar alrededor de la media.

In [5]:
a=np.random.normal(5,0.8,(10,2))
print(a)

[[5.50894835 4.31165061]
 [4.22521955 4.59891188]
 [4.65884827 4.32873899]
 [4.32556855 4.61966718]
 [4.02209641 4.73860086]
 [4.48593959 4.69054105]
 [4.89649628 4.5773106 ]
 [2.82968942 4.09817978]
 [4.59576408 3.75225172]
 [6.35670575 4.9802934 ]]


e)Crear un array con el comando linspace.

Esta función que divide en partes definida iguales desde un número hasta otro punto a diferencia de cuando usamos el arange le decimos el step y la cantidad de elementos varian 

In [6]:
a=np.linspace(1,10,100)
print(a)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

a)Crear dos arrays y aplicar las operaciones arr1 + arr2 y arr1*arr2. ¿Qué condiciones deben cumplir arr1 y arr2?

para realizar las operaciones arr1 + arr2 y arr1 * arr2 deben cumplir:

Misma dimensión: Los arrays deben tener el mismo número de dimensiones y el mismo tamaño en cada dimensión.

suman y multiplican elemento por elemento



In [7]:
arr1=np.array([[3,4,5],[6,7,8]])
arr2=np.array([[9,10,11],[12,13,14]])
arr_suma=arr1+arr2
arr_mult=arr1*arr2
print(f"la suma de arr1:{arr1} + arr2: {arr2} es arr_suma: {arr_suma}")
print(f"la multiplicación de arr1:{arr1} * arr2: {arr2} es arr_mult: {arr_mult}")

la suma de arr1:[[3 4 5]
 [6 7 8]] + arr2: [[ 9 10 11]
 [12 13 14]] es arr_suma: [[12 14 16]
 [18 20 22]]
la multiplicación de arr1:[[3 4 5]
 [6 7 8]] * arr2: [[ 9 10 11]
 [12 13 14]] es arr_mult: [[ 27  40  55]
 [ 72  91 112]]


b)Verificar la multiplicación de un escalar por un array.

In [8]:
escalar=2
arr=escalar*arr1
print(f"la multiplicación de un escalar: {escalar} y de arr1:{arr1} es el nuevo arr: {arr}")

la multiplicación de un escalar: 2 y de arr1:[[3 4 5]
 [6 7 8]] es el nuevo arr: [[ 6  8 10]
 [12 14 16]]


c)De un array de 2D obtener la matriz traspuesta.

In [9]:
print(f"el arr1: {arr1} es de dim:{arr1.ndim}")
matriz_traspuesta=arr1.transpose()
print(f"la traspuesta de el arr1: {arr1} es matriz_traspuesta:{matriz_traspuesta}")

el arr1: [[3 4 5]
 [6 7 8]] es de dim:2
la traspuesta de el arr1: [[3 4 5]
 [6 7 8]] es matriz_traspuesta:[[3 6]
 [4 7]
 [5 8]]


d)Realizar la multiplicación de dos matrices de dimensiones apropiadas.

para realizar las operaciones matriciales de arr1 @ arr2 deben cumplir:

La cantidad de columnas del primer array (arr1) debe ser igual a la cantidad de filas del segundo array (arr2).

In [10]:
arr_mult_matricial=arr1@matriz_traspuesta

print(f"la multiplicación matricial de arr1:{arr1} @ arr2: {matriz_traspuesta} es arr_mult_matricial: {arr_mult_matricial}")

la multiplicación matricial de arr1:[[3 4 5]
 [6 7 8]] @ arr2: [[3 6]
 [4 7]
 [5 8]] es arr_mult_matricial: [[ 50  86]
 [ 86 149]]


Problema 3: Indexación y slicing de arrays de NumPy.

a) Crear un array de dimensión (4,4) y extraer: el elemento de la fila 3 y columna 2; la segunda fila; y la tercera columna.

Indexación y slicing de arrays de NumPy
La indexación y el slicing son dos herramientas fundamentales para acceder a elementos específicos o subconjuntos de elementos dentro de arrays de NumPy. Estas técnicas permiten seleccionar y manipular datos de manera eficiente en diversas aplicaciones de computación científica y análisis de datos.

1. Indexación básica:

La indexación básica se utiliza para acceder a un elemento específico dentro de un array. Se utiliza la notación de corchetes [] donde se indica la posición del elemento deseado.
La posición del elemento se define por un índice entero. El primer elemento tiene índice 0, el segundo índice 1, y así sucesivamente.

Ejemplo: arr = np.array([1, 2, 3]); print(arr[0]) imprime el elemento en la posición 0 (resultado: 1).

2. Indexación negativa:

La indexación negativa permite acceder a elementos desde el final del array. El primer elemento desde el final tiene índice -1, el segundo índice -2, y así sucesivamente.
Ejemplo: arr = np.array([1, 2, 3]); print(arr[-1]) imprime el último elemento (resultado: 3).

3. Indexación con múltiples dimensiones:

Para arrays multidimensionales (matrices, etc.), se utilizan múltiples conjuntos de corchetes separados por comas para acceder a elementos específicos en cada dimensión.
Ejemplo: arr = np.array([[1, 2], [3, 4]]); print(arr[1, 0]) imprime el elemento en la fila 1 y columna 0 (resultado: 3).
4. Slicing:

El slicing permite seleccionar subconjuntos de elementos dentro de un array. Se utiliza la notación de dos puntos : dentro de los corchetes [].
La sintaxis básica es arr[start:stop], donde start indica el índice inicial (inclusivo) y stop indica el índice final (exclusivo).
Ejemplo: arr = np.array([1, 2, 3, 4, 5]); print(arr[1:3]) imprime un subarray desde la posición 1 hasta la 2 (resultado: [2, 3]).
5. Slicing con paso:

Se puede especificar un paso para seleccionar elementos a intervalos regulares dentro del subarray. Se utiliza la sintaxis arr[start:stop:step].
El valor de step indica la distancia entre los elementos seleccionados.
Ejemplo: arr = np.array([1, 2, 3, 4, 5]); print(arr[1:5:2]) imprime elementos impares desde la posición 1 hasta la 5 (resultado: [2, 4]).
6. Slicing con índices negativos:

El slicing también funciona con índices negativos para seleccionar subarrays desde el final del array.
Ejemplo: arr = np.array([1, 2, 3, 4, 5]); print(arr[-2:]) imprime un subarray desde la penúltima posición hasta el final (resultado: [4, 5]).
7. Slicing con booleanos:

Se pueden utilizar arrays booleanos como índices para seleccionar elementos específicos o subconjuntos de elementos.
Ejemplo: arr = np.array([1, 2, 3, 4, 5]); mask = arr > 2; print(arr[mask]) imprime los elementos mayores que 2 (resultado: [3, 4, 5]).

In [11]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr)
print(f"el elemetno de la fila 3 y columna 2 es: {arr[2][1]}")

print(f"se imprimen los elemetnos de la fila 2: {arr[1,:]}")
print(f"se imprimen los elemetnos de la columna 3: {arr[:,2]}")





[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
el elemetno de la fila 3 y columna 2 es: 10
se imprimen los elemetnos de la fila 2: [5 6 7 8]
se imprimen los elemetnos de la columna 3: [ 3  7 11 15]


b) Del array del ejercicio anterior, ¿Qué pasa si hacemos arr[1] = np.array([10,10,10,10])?


In [12]:
arr[1] = np.array([10,10,10,10])
print(arr)

[[ 1  2  3  4]
 [10 10 10 10]
 [ 9 10 11 12]
 [13 14 15 16]]


c) ¿Y qué pasa si hacemos arr[1] = 99?

In [13]:
arr[1] = 99
print(arr)

[[ 1  2  3  4]
 [99 99 99 99]
 [ 9 10 11 12]
 [13 14 15 16]]


Problema 4: Manipulación de arrays en NumPy.

a)Crear un array de 12 elementos en una fila. Utilizar el comando reshape(). ¿Qué argumentos de entrada puede tomar? Mostrar dos ejemplos.

La función reshape() en NumPy y Python se utiliza para cambiar la forma de un array sin modificar sus datos. Esto significa que se puede redistribuir los elementos del array en una nueva estructura dimensional, manteniendo el mismo contenido numérico.

numpy.reshape(array, newshape, order='C')

array: El array que se desea redimensionar.

newshape: Una tupla que especifica la nueva forma deseada para el array. La longitud de la tupla debe ser igual al número de dimensiones del array original.

order (opcional): Un string que indica el orden de llenado del nuevo array. Los valores válidos
son 'C' (orden C contiguo) y 'F' (orden Fortran contiguo). El valor por defecto es 'C'.

En resumen, la función reshape() es una herramienta fundamental para manipular la forma de los arrays de NumPy y Python, permitiendo una redistribución flexible de los datos sin alterar su contenido.

In [14]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr_reshape=np.reshape(arr,(3,4))

print(arr)
print(arr_reshape)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


b)En el array del ejercicio anterior, aplicar el comando split(). Mostrar 3 ejemplos.

La función np.split() en NumPy es una herramienta fundamental para dividir arrays multidimensionales en subarrays de tamaños (casi) iguales a lo largo de un eje especificado. Es particularmente útil para procesar y analizar datos estructurados en arrays NumPy.

np.array_split(array, indices_or_sections, axis=None)

array: 
El array NumPy que se desea dividir.

indices_or_sections:
Si es un entero (N), divide el array en N subarrays de tamaño igual a lo largo del eje especificado. El array se divide de la manera más uniforme posible, con un posible resto distribuido entre los subarrays al final.
Si es una lista de enteros ([i1, i2, ..., iK]), divide el array en subarrays en los índices especificados. Los subarrays tendrán tamaños variables, correspondientes a las distancias entre los índices adyacentes.

axis (opcional): El eje a lo largo del cual se realiza la división. El valor predeterminado es 0 (filas para arrays 2D).


In [15]:
sub_arr=np.split(arr,4)
print(sub_arr)

sub_arr=np.split(arr,4,0)
print(sub_arr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


c)Crear dos arrays de 1D y usar el operador concatenate. Luego usar el mismo operador en dos arrays de dimensión (2,2). Probar con el parámetro axis= 0, y axis=1.

La función concatenate en NumPy es una herramienta fundamental para combinar arrays a lo largo de un eje especificado, creando un nuevo array con los elementos de los arrays originales concatenados. Es esencial para construir estructuras de datos más complejas y realizar operaciones avanzadas en arrays NumPy.

np.concatenate(arrays, axis=None, out=None)
arrays: Una secuencia de arrays que se desean concatenar (puede ser una lista, tupla o cualquier iterable).

axis (opcional): El eje a lo largo del cual se realiza la concatenación. El valor predeterminado es None (convierte todos los arrays a una dimensión y luego los concatena).

out (opcional): Un array opcional en el que se almacena el resultado de la concatenación. Si se omite, se crea un nuevo array.

In [16]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1)
print(arr2)

concatenated_array = np.concatenate((arr1, arr2), axis=0)

print(concatenated_array)

arr1 = np.array([[1, 2],[4,5]])
arr2 = np.array([[7,8],[10,11]])

print(arr1)
print(arr2)

concatenated_array = np.concatenate((arr1, arr2), axis=1)
print(concatenated_array)

concatenated_array = np.concatenate((arr1, arr2), axis=0)
print(concatenated_array)


[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
[[1 2]
 [4 5]]
[[ 7  8]
 [10 11]]
[[ 1  2  7  8]
 [ 4  5 10 11]]
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]


Problema 5: Operaciones estadísticas en NumPy.

a)Crear un array de dimensión (3,3) y aplicar los métodos mean(), std(), var() y sum().

mean() (Media):
Calcula la media aritmética de los elementos de un array NumPy.

std() (Desviación estándar):
Estima la desviación estándar de los elementos de un array NumPy. Representa la variabilidad de los datos en torno a la media.

var() (Varianza):
Calcula la varianza de los elementos de un array NumPy. Es el cuadrado de la desviación estándar.

std = sqrt( mean( (x - mean(x))^2 ) )

Donde:
std es la desviación estándar.
sqrt es la función raíz cuadrada.
mean(x) es la media aritmética de todos los elementos en el array x.
(x - mean(x)) es la diferencia de cada elemento x con respecto a la media.
mean((x - mean(x))^2) es la media de los cuadrados de las diferencias.

sum() (Suma):
Calcula la suma de todos los elementos de un array NumPy.




In [17]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.mean())
print(arr.std())
print(arr.var())
print(arr.sum())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
2.581988897471611
6.666666666666667
45


b)Repetir el ejercicio anterior utilizando el parámetro axis=0 y axis=1.

In [18]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.mean(axis=0))
print(arr.std(axis=0))
print(arr.var(axis=0))
print(arr.sum(axis=0))


print(arr.mean(axis=1))
print(arr.std(axis=1))
print(arr.var(axis=1))
print(arr.sum(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4. 5. 6.]
[2.44948974 2.44948974 2.44948974]
[6. 6. 6.]
[12 15 18]
[2. 5. 8.]
[0.81649658 0.81649658 0.81649658]
[0.66666667 0.66666667 0.66666667]
[ 6 15 24]



Problema 6: Utilización de booleanos en NumPy.
a)Crear un arreglo de 4 elementos y aplicar la máscara [False, True, True, False]. ¿Qué resulta?

In [19]:
arr=np.array([1,2,3,4])
mask=np.array([False, True, True, False])
print(arr[mask])


[2 3]


b)Crear un arreglo unidimensional de números enteros aleatorios y filtrar por los valores mayores al promedio, números impares y números pares menores al promedio.



In [20]:
arr=np.random.randint(1,20,10)
print(arr)

print(arr[arr>arr.mean()])

print(arr[arr%2!=0])

print(arr[((arr%2==0) & (arr<arr.mean()))])


[11 18 16  3 17 17  4 18 18 13]
[18 16 17 17 18 18]
[11  3 17 17 13]
[4]


c) En un arreglo bidimensional A de valores aleatorios enteros, ¿qué diferencia hay entre hacer A > A.mean() y A [A> A.mean()]?

In [21]:
arr=np.random.choice(np.arange(1,20),(5,5),replace=True)
print(arr)
print(arr.ndim)
print(arr.mean())
print(arr>arr.mean())

print(arr[arr>arr.mean()])

[[ 6  2  3 11  4]
 [ 3  9 10 18  4]
 [16 11 11  1 17]
 [ 2  3  7 15 15]
 [ 7  5  6  8 16]]
2
8.4
[[False False False  True False]
 [False  True  True  True False]
 [ True  True  True False  True]
 [False False False  True  True]
 [False False False False  True]]
[11  9 10 18 16 11 11 17 15 15 16]
